# frozen_string_literal: true
#
# This file is likely only useful if you're developing a rails application.
#
# Most of this file is left as the default generated by rails.
# However, we also setup access to our ettin configuration here.
# In general, we prefer configuration to be in config/initializers
# for rails applications.

require_relative "boot"
require "rails"

# Pick frameworks as appropriate
require "active_model/railtie"
require "active_job/railtie"
require "active_record/railtie"
require "action_controller/railtie"
require "action_mailer/railtie"
require "action_view/railtie"
require "action_cable/engine"
require "sprockets/railtie"
# require "rails/test_unit/railtie"

Bundler.require(*Rails.groups)

module ProjectTemplate
  class << self
    def config
      @config ||= Ettin.for(Ettin.settings_files('config', Rails.env))
    end
  end

  # eager load
  self.config

  class Application < Rails::Application
    config.middleware.insert_before 0, Rack::Cors do
      allow do
        origins "*"
        resource "*", headers: :any, methods: :any
      end
    end

    # Initialize configuration defaults for originally generated Rails version.
    config.load_defaults 5.1
    config.autoload_paths << Rails.root.join("lib")
  end
end
